spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fatec?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&useTimezone=true&serverTimezone=UTC
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true